ImageX/ImageX/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^photos/', include('photos.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ImageX/photos/urls.py
from django.conf.urls import url
from . import views

app_name = 'photos'

urlpatterns =[
    #/photos
    url(r'^$', views.index, name='index'),
    #/photos/1
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #/photos/picture/add
    url(r'picture/add/$', views.PictureCreate.as_view(), name='picture-add'),
]

ImageX/photos/models.py
from django.db import models
from django.urls import reverse

class Gallery(models.Model):
    creater = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    logo = models.CharField(max_length=1000)
    def __str__(self):
        return self.title

class Photographer(models.Model):
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    
    def __str__(self):
        return "Photographer is" + self.name

class Tag(models.Model):
    text = models.CharField(max_length=100)
    
    def __str__(self):
        return "#" + self.text
    
class Category(models.Model):
    text = models.CharField(max_length=100)
    
    def __str__(self):
        return self.text

class Picture(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=2000)
    file = models.FileField()
    uploader_name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    
    def get_absolute_url(self):
        return reverse('photos:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.title + '-' + self.description

ImageX/photos/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

ImageX/photos/views.py
from django.http import HttpResponse
from .models import Picture, Tag
from django.http import Http404
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .forms import UserForm
#forms
from django.views.generic.edit import CreateView, UpdateView, DeleteView

def index(request):
    
    '''
    picture_set = Picture.objects.all()
    query = request.GET.get("q")
    if query:
        picture = picture_set.filter(
            title__icontains=query
        ).distinct()
        return render(request, 'index.html', {'pictures': picture,})
    else:
        return render(request, 'index.html', {'pictures': picture_set})
    
    '''
    query = request.GET.get("q")
    try:
        #1 Get the Tag Object
        requiredTag = Tag.objects.all().get(text=query)
        #2 Get the Photo Objects associated with the Tag
        requiredPicture = requiredTag.picture_set.all().distinct()
    except Tag.DoesNotExist:
        requiredTag = None
        requiredPicture = Picture.objects.all()
    return render(request, 'index.html', {'pictures': requiredPicture})
        


class DetailView(generic.DetailView):
    model = Picture
    template_name ='detail.html'


class PictureCreate(CreateView):
    model = Picture
    fields = ['title', 'description', 'category', 'file', 'uploader_name']
    #Create a Form for Tag
    #Add-to/Create Tags
    def form_valid(self, form):
        my_picture_uploader = form.instance.uploader_name
        pictures = Picture.objects.all()
        num = pictures.filter(uploader_name=my_picture_uploader).count()
        if num < 3:
            success = True
        else:
            success = False
        if success:
            return super(PictureCreate, self).form_valid(form)
        else:
            return HttpResponse("User Can't Upload too many Photos")

ImageX/photos/templates/detail.html
{% extends 'topbar.html' %}

{% block body %}
<p1>Picture Title: {{ object.title }}</p1><br>
<p1>Picture Description: {{ object.description }}</p1><br>
<p1>Picture Category: {{ object.category }} </p1><br>
<p1>Picture Tag: {{ object.tag }}</p1><br>
    <p1>Uploader: {{ object.uploader_name }}</p1><br>


<img src="{{ object.file.url }}" width="300" height="200">
{% endblock %}

ImageX/photos/templates/form-template.html
{% for field in form %}
    <div class=""form-group>
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="sol-sm-10">{{ field }}</div>
    </div>
{% endfor %}

ImageX/photos/templates/index.html
{% extends 'topbar.html' %}

{% block body %}
<div class="albums-container container-fluid">
    <!-- If user searches and there are songs -->
    {% if pictures %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Picture</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Picture Title</th>
                                    <th>Picture Description</td>
                                    <td>Picture</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for picture in pictures %}
                                    <tr>
                                        <td>{{ picture.title }}</td>
                                        <td>{{ picture.description }}</td>
                                        <td>
                                            <img src="{{ picture.file.url }}" width="300" height="200">
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

ImageX/photos/templates/photos/detail.html
<p1>{{ object.title }}</p1>
<p2>{{ object.description }}</p2>
<img src="{{ object.file.url }}">

ImageX/photos/templates/photos/picture_form.html
{% extends 'topbar.html' %}
{% block body %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

ImageX/photos/templates/picture_form.html
{% extends 'topbar.html' %}

{% block body %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

ImageX/photos/templates/topbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ImageX</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>
<nav class ="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header navbar-brand">
            ImageX
        </div>


        <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'photos:index' %}">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'photos:picture-add' %}">
                    <span>Upload</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>